apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - kubeflow-training-roles.yaml
images:
  - name: kubeflow/training-operator
    newName: public.ecr.aws/j1r0q0g6/training/training-operator
    newTag: "8c4323194a09b3cabd36248cc172493006f71b75"
